[program:nginx]
command=/etc/router/nginx-service.sh
priority=100
stdout_logfile=/var/log/%(program_name)s/stdout.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/var/log/%(program_name)s/stderr.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=3
